version: "3"
services:
    mysql-integrador:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./DataBase:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
        - 3307:3306
    server-integrador:
        build: "./Server"
        image: server-integrador
        working_dir: /app
        command: npm start
        volumes:
            - ./Server:/app
        restart: always
        depends_on:
            - mysql-integrador
        ports:
        - "3002:3000"
    cliente-integrador:
        build: "./Client/integrador-app"
        image: cliente-integrador
        working_dir: /app
        command: npm start
        volumes:
            - ./Client/integrador-app:/app
        ports:
        - "3000:3000"
        restart: always
        stdin_open: true